import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const generated = resolve(root, 'src/interactiveViewer.generated.ts');

/** Bundle the offline viewer into one script while keeping its source in normal TS/CSS files. */
export async function buildViewer() {
  const result = await build({
    entryPoints: [resolve(root, 'src/interactiveViewer.ts')],
    bundle: true,
    write: false,
    platform: 'browser',
    format: 'iife',
    target: 'es2020',
    minify: true,
  });
  const script = result.outputFiles[0].text.replaceAll('</script', '<\\/script');
  const css = await readFile(resolve(root, 'src/interactiveViewer.css'), 'utf8');
  const output = `// Generated by scripts-build-viewer.ts; do not edit directly.\nexport const VIEWER_CSS = ${JSON.stringify(css)};\nexport const VIEWER_SCRIPT = ${JSON.stringify(script)};\n`;
  if (await readFile(generated, 'utf8').catch(() => '') !== output) await writeFile(generated, output);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await buildViewer();
