// @ts-nocheck
// Offline viewer entry. The build script bundles its shared imports into one inline script.
import { dayNumber, dateString, makeCalendar } from './dateCalendar';
import { alignStart, pixelsPerDay, timeColumns } from './timeline';
import { dependencyFocus, displayDependencyEdges, ganttTreeLayout, visibleTaskUids } from './ganttLayout';
import { dependencyCurve } from './ganttGeometry';
import { GANTT_BAR_TOP, GANTT_LAYOUT_SIZING, GANTT_PARENT_INSET, GANTT_PARENT_MIN_HEIGHT, GANTT_SIZING } from './ganttSizing';
import { GANTT_ZOOM_LEVELS } from './ganttZoom';
(function(){
  'use strict';
  var payload=JSON.parse(document.getElementById('task-manager-data').textContent);
  var project=payload.project, statusColors=payload.statusColors, tasks=project.tasks.slice().sort(function(a,b){return a.order-b.order}), byUid=new Map(tasks.map(function(t){return[t.uid,t]})),parentUids=new Set(tasks.filter(function(t){return t.parent_uid}).map(function(t){return t.parent_uid})),dependencyEdges=payload.dependencies;
  var schedules=new Map(payload.schedules.map(function(s){return[s.uid,s]})),calendar=makeCalendar(project);
  document.documentElement.style.setProperty('--gantt-parent-label-top', GANTT_SIZING.parentLabelTop+'px');
  var state={scale:payload.view.scale,labels:payload.view.filter.labels.slice(),mode:payload.view.filter.mode,query:'',selected:null,hover:null,zoom:1},pan=null,suppressClick=false;
  var labelWidth=280,scroll=document.getElementById('scroll'), details=document.getElementById('details');
  function slotText(slot){var day=Math.floor(slot/2);return dateString(day)+' '+(slot%2===0?'上午':'下午')}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function childrenMap(){var map=new Map();tasks.forEach(function(t){var key=t.parent_uid||'';if(!map.has(key))map.set(key,[]);map.get(key).push(t)});return map}
  function layout(){var map=childrenMap(),visible=state.selected?dependencyFocus(project,state.selected,dependencyEdges).visibleUids:visibleTaskUids(project,{labels:state.labels,mode:state.mode},state.query),tree=ganttTreeLayout(project,visible,GANTT_LAYOUT_SIZING);return{items:tree.items,height:Math.max(360,tree.height),visible:visible,map:map}}
  function relationSet(uid,edgeList){var set=new Set(uid?[uid]:[]);if(uid)edgeList.forEach(function(e){if(e.from===uid||e.to===uid){set.add(e.from);set.add(e.to)}});return set}
  function render(){var oldLeft=scroll.scrollLeft,oldTop=scroll.scrollTop,tree=layout(),items=tree.items,itemMap=new Map(items.map(function(i){return[i.task.uid,i]})),displayed=new Set(itemMap.keys()),edgeList=displayDependencyEdges(project,displayed,dependencyEdges),focus=state.selected||state.hover,related=relationSet(focus,edgeList),ppd=pixelsPerDay[state.scale]*state.zoom;
    var scheduled=items.map(function(i){return schedules.get(i.task.uid)}).filter(Boolean),origin=alignStart(Math.min.apply(null,[dayNumber(project.project.start_date)-2].concat(scheduled.map(function(s){return Math.floor(s.start/2)-2}))),state.scale),end=Math.max.apply(null,[origin+Math.ceil(Math.max(1000,window.innerWidth-labelWidth-50)/ppd)].concat(scheduled.map(function(s){return Math.ceil(s.end/2)+10}))),width=Math.max(1000,Math.ceil((end-origin)*ppd)),height=tree.height;
    document.getElementById('range').textContent=dateString(origin)+' — '+dateString(end-1);document.getElementById('count').textContent=items.length+' / '+tasks.length+' 条任务';
    state.origin=origin;state.ppd=ppd;
    var axis=timeColumns(origin,end,state.scale).map(function(c){return '<div class="axis-cell" style="left:'+((c.start-origin)*ppd)+'px;width:'+((c.end-c.start)*ppd)+'px">'+esc(c.label)+(state.scale==='day'?'<small>上午　下午</small>':'')+'</div>'}).join('');
    var rest='';if(ppd>=3&&end-origin<=5000){for(var day=origin;day<end;day++){if(!calendar(dateString(day)).isWorkday)rest+='<i class="rest" style="left:'+((day-origin)*ppd)+'px;width:'+ppd+'px"></i>'}}
    var labels=items.map(function(i){var dim=focus&&!related.has(i.task.uid),kids=(tree.map.get(i.task.uid)||[]).length,collapsed=kids&&i.task.collapse_children;return '<div class="label '+(i.isParent?'parent ':'')+(related.has(i.task.uid)?'related ':'')+(dim?'dim':'')+'" data-uid="'+esc(i.task.uid)+'" style="top:'+(i.top+(i.isParent?GANTT_PARENT_INSET:GANTT_BAR_TOP))+'px;height:'+GANTT_SIZING.barHeight+'px;padding-left:'+(10+i.depth*17)+'px"><button class="twisty" data-collapse="'+esc(i.task.uid)+'" '+(!kids?'disabled':'')+'>'+(kids?(collapsed?'▸':'▾'):'')+'</button><span class="order">'+i.task.order+'</span><span class="name">'+esc(i.task.name)+'</span>'+(!i.isParent?'<span class="assignee">'+esc(i.task.assignee)+'</span>':'')+'</div>'}).join('');
    var bars=items.map(function(i){var t=i.task,s=schedules.get(t.uid);if(!s)return'';var left=(s.start-origin*2)*ppd/2,barWidth=Math.max(8,(s.end-s.start)*ppd/2),parent=i.isParent,color=statusColors[t.status],dim=focus&&!related.has(t.uid),style=(parent&&!t.collapse_children?'background:transparent;':'background:'+color.fill+';')+'border-color:'+color.border+';color:'+color.text+';left:'+left+'px;width:'+barWidth+'px;top:'+(i.top+(parent?GANTT_PARENT_INSET:GANTT_BAR_TOP))+'px;height:'+(parent?Math.max(GANTT_PARENT_MIN_HEIGHT,i.height-(GANTT_PARENT_INSET * 2)):GANTT_SIZING.barHeight)+'px';return '<div class="bar '+(parent?'parent ':'')+(parent&&!t.collapse_children?'expanded ':'')+(s.late?'late ':'')+(related.has(t.uid)?'related ':'')+(state.selected===t.uid?'selected ':'')+(dim?'dim':'')+'" data-uid="'+esc(t.uid)+'" style="'+style+'"><span>'+esc(t.name)+'</span></div>'}).join('');
    var paths=edgeList.map(function(e){var a=schedules.get(e.from),b=schedules.get(e.to),from=itemMap.get(e.from),to=itemMap.get(e.to);if(!a||!b||!from||!to)return'';var ax=(a.end-origin*2)*ppd/2,ay=from.top+(GANTT_SIZING.rowHeight / 2),bx=(b.start-origin*2)*ppd/2,by=to.top+(GANTT_SIZING.rowHeight / 2),curve=dependencyCurve({x:ax,y:ay},{x:bx,y:by}),isRelated=focus&&(e.from===focus||e.to===focus);return '<g class="edge '+(e.kind==='assignee'?'assignee ':'explicit ')+(isRelated?'related ':'')+(focus&&!isRelated?'dim':'')+'" data-from="'+esc(e.from)+'" data-to="'+esc(e.to)+'"><path d="'+curve.path+'"></path><line class="edge-arrowhead" x1="'+curve.arrowStart.x+'" y1="'+curve.arrowStart.y+'" x2="'+curve.arrowEnd.x+'" y2="'+curve.arrowEnd.y+'" marker-end="url(#arrow)"></line></g>'}).join('');
    document.getElementById('canvas').style.width=(width+labelWidth)+'px';document.getElementById('labels-head').style.width=labelWidth+'px';document.getElementById('axis').style.cssText='left:'+labelWidth+'px;width:'+width+'px';document.getElementById('axis').innerHTML=axis;
    document.getElementById('body').style.height=height+'px';document.getElementById('grid').style.cssText='left:'+labelWidth+'px;width:'+width+'px;background-size:'+ppd+'px 100%';document.getElementById('grid').innerHTML=rest+'<i class="today" style="left:'+((dayNumber(payload.today)-origin)*ppd)+'px"><span>今天</span></i>';
    document.getElementById('labels').style.cssText='width:'+labelWidth+'px;height:'+height+'px;transform:translateX('+scroll.scrollLeft+'px)';document.getElementById('labels').innerHTML=labels;document.getElementById('bars').style.cssText='left:'+labelWidth+'px;width:'+width+'px;height:'+height+'px';document.getElementById('bars').innerHTML=bars;document.getElementById('edges').setAttribute('width',String(width));document.getElementById('edges').setAttribute('height',String(height));document.getElementById('edges').style.left=labelWidth+'px';document.getElementById('edge-paths').innerHTML=paths;
    bindTasks();scroll.scrollLeft=oldLeft;scroll.scrollTop=oldTop;showDetails(state.selected)
  }
  function applyFocus(){var focus=state.selected||state.hover,related=new Set(focus?[focus]:[]);document.querySelectorAll('.edge').forEach(function(edge){var hit=focus&&(edge.dataset.from===focus||edge.dataset.to===focus);edge.classList.toggle('related',!!hit);edge.classList.toggle('dim',!!state.selected&&!hit);if(hit){related.add(edge.dataset.from);related.add(edge.dataset.to)}});document.querySelectorAll('[data-uid]').forEach(function(el){var hit=related.has(el.dataset.uid);el.classList.toggle('related',hit);el.classList.toggle('dim',!!state.selected&&!hit);el.classList.toggle('selected',el.classList.contains('bar')&&state.selected===el.dataset.uid)})}
  function bindTasks(){document.querySelectorAll('[data-uid]').forEach(function(el){el.addEventListener('mouseenter',function(){state.hover=el.dataset.uid;applyFocus()});el.addEventListener('mouseleave',function(){state.hover=null;applyFocus()});el.addEventListener('click',function(e){if(suppressClick){suppressClick=false;e.preventDefault();e.stopPropagation();return}if(e.target.closest('[data-collapse]')||parentUids.has(el.dataset.uid))return;state.selected=state.selected===el.dataset.uid?null:el.dataset.uid;render()})});document.querySelectorAll('[data-collapse]').forEach(function(el){el.addEventListener('click',function(e){e.stopPropagation();var t=byUid.get(el.dataset.collapse);t.collapse_children=!t.collapse_children;render()})})}
  function showDetails(uid){if(!uid){details.hidden=true;return}var t=byUid.get(uid),s=schedules.get(uid),incoming=dependencyEdges.filter(function(e){return e.to===uid}).map(function(e){return(byUid.get(e.from)&&byUid.get(e.from).name||e.from)+(e.kind==='assignee'?'（自动串行）':'')}),outgoing=dependencyEdges.filter(function(e){return e.from===uid}).map(function(e){return(byUid.get(e.to)&&byUid.get(e.to).name||e.to)+(e.kind==='assignee'?'（自动串行）':'')});details.hidden=false;details.innerHTML='<button class="close" aria-label="关闭">×</button><h2>'+esc(t.name)+'</h2><small>'+esc(t.uid)+'</small>'+(t.description?'<div class="desc">'+esc(t.description)+'</div>':'')+'<dl><dt>状态</dt><dd>'+esc(t.status)+'</dd><dt>执行人</dt><dd>'+esc(t.assignee)+'</dd><dt>计算排期</dt><dd>'+(s?slotText(s.start)+' — '+slotText(s.end-1):'—')+(s&&s.late?' <span class="warning">超期</span>':'')+'</dd><dt>预计耗时</dt><dd>'+t.duration_days+' 天</dd><dt>前置任务</dt><dd>'+esc(incoming.join('、')||'无')+'</dd><dt>后续任务</dt><dd>'+esc(outgoing.join('、')||'无')+'</dd><dt>标签</dt><dd>'+t.labels.map(function(x){return'<span class="pill">'+esc(x)+'</span>'}).join('')+'</dd></dl>';details.querySelector('.close').addEventListener('click',function(){state.selected=null;render()})}
  document.querySelectorAll('[data-scale]').forEach(function(b){b.addEventListener('click',function(){state.scale=b.dataset.scale;document.querySelectorAll('[data-scale]').forEach(function(x){x.classList.toggle('active',x===b)});render()})});
  document.getElementById('search').addEventListener('input',function(e){state.query=e.target.value;state.selected=null;render()});document.getElementById('mode').value=state.mode;document.getElementById('mode').addEventListener('change',function(e){state.mode=e.target.value;render()});
  var labelFilter=document.getElementById('labels-filter');labelFilter.innerHTML=[''].concat(payload.labels).map(function(x){return'<option value="'+esc(x)+'">'+(x?esc(x):'全部标签')+'</option>'}).join('');if(state.labels.length===1)labelFilter.value=state.labels[0];else if(state.labels.length>1){labelFilter.insertAdjacentHTML('beforeend','<option value="__current_filter__">当前筛选：'+esc(state.labels.join('、'))+'</option>');labelFilter.value='__current_filter__'}labelFilter.addEventListener('change',function(e){if(e.target.value==='__current_filter__')return;state.labels=e.target.value?[e.target.value]:[];render()});
  function changeZoom(next){if(GANTT_ZOOM_LEVELS.indexOf(next)<0||next===state.zoom)return;var timelineWidth=Math.max(0,scroll.clientWidth-labelWidth),anchor=state.origin*2+(scroll.scrollLeft+timelineWidth/2)*2/state.ppd;state.zoom=next;render();scroll.scrollLeft=Math.max(0,(anchor-state.origin*2)*state.ppd/2-timelineWidth/2)}
  document.getElementById('zoom-in').addEventListener('click',function(){var index=GANTT_ZOOM_LEVELS.indexOf(state.zoom);changeZoom(GANTT_ZOOM_LEVELS[Math.min(GANTT_ZOOM_LEVELS.length-1,index+1)])});document.getElementById('zoom-out').addEventListener('click',function(){var index=GANTT_ZOOM_LEVELS.indexOf(state.zoom);changeZoom(GANTT_ZOOM_LEVELS[Math.max(0,index-1)])});document.getElementById('reset').addEventListener('click',function(){state.selected=null;state.hover=null;state.query='';state.labels=[];state.zoom=1;document.getElementById('search').value='';document.getElementById('labels-filter').value='';render();scroll.scrollLeft=0});
  document.body.addEventListener('click',function(e){if(suppressClick){suppressClick=false;return}if(!state.selected)return;var taskTarget=e.target.closest('[data-uid]');if(taskTarget&&!parentUids.has(taskTarget.dataset.uid))return;state.selected=null;state.hover=null;render()});scroll.addEventListener('scroll',function(){document.getElementById('labels').style.transform='translateX('+scroll.scrollLeft+'px)'});
  scroll.addEventListener('pointerdown',function(e){if(e.button!==0||e.target.closest('button,input,select')||e.target.closest('.bar[data-uid]:not(.parent)'))return;pan={pointerId:e.pointerId,x:e.clientX,y:e.clientY,left:scroll.scrollLeft,top:scroll.scrollTop,moved:false};scroll.classList.add('panning');scroll.setPointerCapture(e.pointerId)});scroll.addEventListener('pointermove',function(e){if(!pan||e.pointerId!==pan.pointerId)return;var dx=e.clientX-pan.x,dy=e.clientY-pan.y;if(Math.abs(dx)>4||Math.abs(dy)>4)pan.moved=true;scroll.scrollLeft=pan.left-dx;scroll.scrollTop=pan.top-dy});function endPan(e){if(!pan||e.pointerId!==pan.pointerId)return;if(pan.moved){suppressClick=true;setTimeout(function(){suppressClick=false},0)}pan=null;scroll.classList.remove('panning')}scroll.addEventListener('pointerup',endPan);scroll.addEventListener('pointercancel',endPan);
  document.querySelector('[data-scale="'+state.scale+'"]').classList.add('active');document.getElementById('draft').hidden=!payload.draft;render();
})();
